# Generated by Django 5.0.7 on 2024-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.IntegerField(default=0),
        ),
    ]
